### ISSUE TITLE
User gets a strange blank page when the refresh token expires

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/browse-everything#111]
I'm logging this as an issue.  The user sees a blank list of files and no errors on the front end, and on the back end we get the following error in the logs:

2015-10-20 13:41:59 -0400 (26550) AuthError occured when checking token. Exception RubyBox::AuthError : no data returned. token as expired and need to refresh it
2015-10-20 13:41:59 -0400 (26550) 
ActionView::Template::Error (invalid_grant: Refresh token has expired
{"error":"invalid_grant","error_description":"Refresh token has expired"}):
    13:         <th role="columnheader">Modified</th>
    14:       </tr>
    15:     </thead>
    16:     <% provider.contents(browse_path).each_with_index do |file,index| %>
    17:       <% if is_acceptable?(file) %>
    18:         <%= render :partial => 'file', :locals => { :file => file, :index => index, 
    19:           :path => browse_everything_engine.contents_path(provider_name,file.id), :parent => params[:parent] } %>
  oauth2 (0.9.4) lib/oauth2/client.rb:113:in `request'
  oauth2 (0.9.4) lib/oauth2/client.rb:138:in `get_token'
  oauth2 (0.9.4) lib/oauth2/access_token.rb:86:in `refresh!'
  ruby-box (1.15.0) lib/ruby-box/session.rb:40:in `refresh_token'
  /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.2.0/bundler/gems/browse-everything-e7c83be25ebc/lib/browse_everything/driver/box.rb:102:in `refresh_token'
  /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.2.0/bundler/gems/browse-everything-e7c83be25ebc/lib/browse_everything/driver/box.rb:107:in `box_client'
  /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.2.0/bundler/gems/browse-everything-e7c83be25ebc/lib/browse_everything/driver/box.rb:28:in `contents'

**Comment by atz** [comment]
Essentially the same problem as #100
